#
name: Frontend

description: d3-like api with some built in charts
dependencies:
  color: any
  angular: ^4.0.0
  angular_components: ^0.8.0
  intl: any
  d3: ^0.2.0
#  d3dart: ^0.0.1

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
  - angular:
      entry_points:
        - web/main.dart
        - test/**_test.dart
  - test/pub_serve:
      $include: test/**_test.dart
  - dart_to_js_script_rewriter

version: 0.0.1